/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supply.medium.home.edi;

import java.io.*;
import supply.medium.utility.ErrorMaster;
import supply.medium.utility.SmProperties;

/**
 *
 * @author Vic
 */
public class GenerateEDI {

    public static void generateRFQ(String transKey, String path, String fileName, String fromcompanyKey, String tocompanyKey) {
        String data = "<?xml version='1.0' encoding='UTF-8' standalone='no'?>\n"
                + "<transactionSet>\n"
                + "    <segment code='ST'>\n"
                + "        <name>Transaction Set Header</name>\n"
                + "        <element code='143'>\n"
                + "            <name>Transaction Set Identifier Code</name>\n"
                + "            <value>Request for Quotation</value>\n"
                + "        </element>\n"
                + "        <element code='329'>\n"
                + "            <name>Transaction Set Control Number</name>\n"
                + "            <value>15</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='BQT'>\n"
                + "        <name>Beginning Segment for Request for Quotation</name>\n"
                + "        <element code='353'>\n"
                + "            <name>Transaction Set Purpose Code</name>\n"
                + "            <value>Original</value>\n"
                + "        </element>\n"
                + "        <element code='586'>\n"
                + "            <name>Request for Quote Reference Number</name>\n"
                + "            <value>15</value>\n"
                + "        </element>\n"
                + "        <element code='373'>\n"
                + "            <name>Date</name>\n"
                + "            <value>2013-11-19</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='REF'>\n"
                + "        <name>Reference Identification</name>\n"
                + "        <element code='128'>\n"
                + "            <name>Reference Identification Qualifier</name>\n"
                + "            <value>Vendor ID Number</value>\n"
                + "        </element>\n"
                + "        <element code='127'>\n"
                + "            <name>Reference Identification</name>\n"
                + "            <value>980002334</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='PER'>\n"
                + "        <name>Administrative Communications Contact</name>\n"
                + "        <element code='366'>\n"
                + "            <name>Contact Function Code</name>\n"
                + "            <value code='EB'>Entered By</value>\n"
                + "        </element>\n"
                + "        <element code='93'>\n"
                + "            <name>Name</name>\n"
                + "            <value>Manish, Inc</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <loop code='N1'>\n"
                + "        <segment code='N1'>\n"
                + "            <name>Name</name>\n"
                + "            <element code='98'>\n"
                + "                <name>Entity Identifier Code</name>\n"
                + "                <value code='BY'>Buying Party</value>\n"
                + "            </element>\n"
                + "            <element code='93'>\n"
                + "                <name>Name</name>\n"
                + "                <value>Aayush Varma</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N3'>\n"
                + "            <name>Address Information</name>\n"
                + "            <element code='166'>\n"
                + "                <name>Address Information</name>\n"
                + "                <value/>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N4'>\n"
                + "            <name>Geographic Location</name>\n"
                + "            <element code='19'>\n"
                + "                <name>City Name</name>\n"
                + "                <value>Noida</value>\n"
                + "            </element>\n"
                + "            <element code='156'>\n"
                + "                <name>State or Province Code</name>\n"
                + "                <value>null</value>\n"
                + "            </element>\n"
                + "            <element code='116'>\n"
                + "                <name>Postal Code</name>\n"
                + "                <value>1100203</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N1'>\n"
                + "            <name>Name</name>\n"
                + "            <element code='98'>\n"
                + "                <name>Entity Identifier Code</name>\n"
                + "                <value code='VN'>Vendor</value>\n"
                + "            </element>\n"
                + "            <element code='93'>\n"
                + "                <name>Name</name>\n"
                + "                <value>Manish Varma</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N3'>\n"
                + "            <name>Address Information</name>\n"
                + "            <element code='166'>\n"
                + "                <name>Address Information</name>\n"
                + "                <value/>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N4'>\n"
                + "            <name>Geographic Location</name>\n"
                + "            <element code='19'>\n"
                + "                <name>City Name</name>\n"
                + "                <value>Noida</value>\n"
                + "            </element>\n"
                + "            <element code='156'>\n"
                + "                <name>State or Province Code</name>\n"
                + "                <value>null</value>\n"
                + "            </element>\n"
                + "            <element code='116'>\n"
                + "                <name>Postal Code</name>\n"
                + "                <value>110030</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "    </loop>\n"
                + "    <loop code='PO1'>\n"
                + "        <segment code='PO1'>\n"
                + "            <name>Baseline Item Data</name>\n"
                + "            <element code='350'>\n"
                + "                <name>Assigned Identification</name>\n"
                + "                <value>1</value>\n"
                + "            </element>\n"
                + "            <element code='330'>\n"
                + "                <name>Quantity Ordered</name>\n"
                + "                <value>10.0</value>\n"
                + "            </element>\n"
                + "            <element code='355'>\n"
                + "                <name>Unit or Basis for Measurement Code</name>\n"
                + "                <value>DOZ</value>\n"
                + "            </element>\n"
                + "            <element code='235'>\n"
                + "                <name>Product/Service ID Qualifier</name>\n"
                + "                <value code='MG'>Manufacturer's Part Number</value>\n"
                + "            </element>\n"
                + "            <element code='234'>\n"
                + "                <name>Product/Service ID</name>\n"
                + "                <value>002</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "    </loop>\n"
                + "    <loop code='PID'>\n"
                + "        <segment code='PID'>\n"
                + "            <name>Product/Item Description</name>\n"
                + "            <element code='349'>\n"
                + "                <name>Item Description Type</name>\n"
                + "                <value code='F'>Free-form</value>\n"
                + "            </element>\n"
                + "            <element code='352'>\n"
                + "                <name>Description</name>\n"
                + "                <value>MotherBoards</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "    </loop>\n"
                + "    <segment code='CTT'>\n"
                + "        <name>Transaction Totals</name>\n"
                + "        <element code='354'>\n"
                + "            <name>Number of Line Items</name>\n"
                + "            <value>1</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='SE'>\n"
                + "        <name>Transaction Set Trailer</name>\n"
                + "        <element code='96'>\n"
                + "            <name>Number of Included Segments</name>\n"
                + "            <value>81</value>\n"
                + "        </element>\n"
                + "        <element code='329'>\n"
                + "            <name>Transaction Set Control Number</name>\n"
                + "            <value>15</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "</transactionSet>";
        SmProperties.folderPath = path;

        String filePath = SmProperties.folderPath + "company-" + tocompanyKey + File.separator + "transaction";
        File folder = new File(filePath);
        if (!folder.exists()) {
            folder.mkdirs();
        }

        String fileLocation = filePath + File.separator + fileName + ".xml";
        writeFile(fileLocation, data);

        SmProperties.folderPath = path;

        String filePath2 = SmProperties.folderPath + "company-" + fromcompanyKey + File.separator + "transaction";
        File folder2 = new File(filePath2);
        if (!folder2.exists()) {
            folder2.mkdirs();
        }

        String fileLocation2 = filePath2 + File.separator + fileName + ".xml";
        writeFile(fileLocation2, data);
    }

    public static void generateQTE(String transKey, String path, String fileName, String fromcompanyKey, String tocompanyKey) {
        String data = "<?xml version='1.0' encoding='UTF-8' standalone='no'?>\n"
                + "<transactionSet>\n"
                + "    <segment code='ST'>\n"
                + "        <name>Transaction Set Header</name>\n"
                + "        <element code='143'>\n"
                + "            <name>Transaction Set Identifier Code</name>\n"
                + "            <value>Response To RFQ</value>\n"
                + "        </element>\n"
                + "        <element code='329'>\n"
                + "            <name>Transaction Set Control Number</name>\n"
                + "            <value>11</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='BQR'>\n"
                + "        <name>Beginning Segment for Response To Request for Quotation</name>\n"
                + "        <element code='353'>\n"
                + "            <name>Transaction Set Purpose Code</name>\n"
                + "            <value>Original</value>\n"
                + "        </element>\n"
                + "        <element code='586'>\n"
                + "            <name>Request for Quote Reference Number</name>\n"
                + "            <value>11</value>\n"
                + "        </element>\n"
                + "        <element code='373'>\n"
                + "            <name>Date</name>\n"
                + "            <value>2013-11-19</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='CUR'>\n"
                + "        <name>Currency</name>\n"
                + "        <element code='98'>\n"
                + "            <name>Entity Identifier Code</name>\n"
                + "            <value>Buying Party</value>\n"
                + "        </element>\n"
                + "        <element code='100'>\n"
                + "            <name>Currency Code</name>\n"
                + "            <value>US Dollar</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='REF'>\n"
                + "        <name>Reference Identification</name>\n"
                + "        <element code='128'>\n"
                + "            <name>Reference Identification Qualifier</name>\n"
                + "            <value>Vendor ID Number</value>\n"
                + "        </element>\n"
                + "        <element code='127'>\n"
                + "            <name>Reference Identification</name>\n"
                + "            <value>980545450</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='PER'>\n"
                + "        <name>Administrative Communications Contact</name>\n"
                + "        <element code='366'>\n"
                + "            <name>Contact Function Code</name>\n"
                + "            <value code='EB'>Entered By</value>\n"
                + "        </element>\n"
                + "        <element code='93'>\n"
                + "            <name>Name</name>\n"
                + "            <value>Aayush, Inc</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <loop code='N1'>\n"
                + "        <segment code='N1'>\n"
                + "            <name>Name</name>\n"
                + "            <element code='98'>\n"
                + "                <name>Entity Identifier Code</name>\n"
                + "                <value code='BY'>Buying Party</value>\n"
                + "            </element>\n"
                + "            <element code='93'>\n"
                + "                <name>Name</name>\n"
                + "                <value>Manish Varma</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N3'>\n"
                + "            <name>Address Information</name>\n"
                + "            <element code='166'>\n"
                + "                <name>Address Information</name>\n"
                + "                <value/>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N4'>\n"
                + "            <name>Geographic Location</name>\n"
                + "            <element code='19'>\n"
                + "                <name>City Name</name>\n"
                + "                <value>Noida</value>\n"
                + "            </element>\n"
                + "            <element code='156'>\n"
                + "                <name>State or Province Code</name>\n"
                + "                <value>null</value>\n"
                + "            </element>\n"
                + "            <element code='116'>\n"
                + "                <name>Postal Code</name>\n"
                + "                <value>110030</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N1'>\n"
                + "            <name>Name</name>\n"
                + "            <element code='98'>\n"
                + "                <name>Entity Identifier Code</name>\n"
                + "                <value code='VN'>Vendor</value>\n"
                + "            </element>\n"
                + "            <element code='93'>\n"
                + "                <name>Name</name>\n"
                + "                <value>Aayush Varma</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N3'>\n"
                + "            <name>Address Information</name>\n"
                + "            <element code='166'>\n"
                + "                <name>Address Information</name>\n"
                + "                <value/>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N4'>\n"
                + "            <name>Geographic Location</name>\n"
                + "            <element code='19'>\n"
                + "                <name>City Name</name>\n"
                + "                <value>Noida</value>\n"
                + "            </element>\n"
                + "            <element code='156'>\n"
                + "                <name>State or Province Code</name>\n"
                + "                <value>null</value>\n"
                + "            </element>\n"
                + "            <element code='116'>\n"
                + "                <name>Postal Code</name>\n"
                + "                <value>1100203</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "    </loop>\n"
                + "    <segment code='AMT'>\n"
                + "        <name>Monetary Amount</name>\n"
                + "        <element code=''>\n"
                + "            <name>Amount  Qualifier Code</name>\n"
                + "            <value code='TT'>Total Transaction Amount</value>\n"
                + "            <value>11.0</value>\n"
                + "        </element>\n"
                + "        <element code='782'>\n"
                + "            <name>Monetary Amount</name>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <loop code='PO1'>\n"
                + "        <segment code='PO1'>\n"
                + "            <name>Baseline Item Data</name>\n"
                + "            <element code='350'>\n"
                + "                <name>Assigned Identification</name>\n"
                + "                <value>1</value>\n"
                + "            </element>\n"
                + "            <element code='330'>\n"
                + "                <name>Quantity Ordered</name>\n"
                + "                <value>10.0</value>\n"
                + "            </element>\n"
                + "            <element code='355'>\n"
                + "                <name>Unit or Basis for Measurement Code</name>\n"
                + "                <value>DOZ</value>\n"
                + "            </element>\n"
                + "            <element code='235'>\n"
                + "                <name>Product/Service ID Qualifier</name>\n"
                + "                <value code='MG'>Manufacturer's Part Number</value>\n"
                + "            </element>\n"
                + "            <element code='234'>\n"
                + "                <name>Product/Service ID</name>\n"
                + "                <value>002</value>\n"
                + "            </element>\n"
                + "            <element code='212'>\n"
                + "                <name>Unit Price</name>\n"
                + "                <value>10.0</value>\n"
                + "            </element>\n"
                + "            <element code='639'>\n"
                + "                <name>Basis of Unit Price Code</name>\n"
                + "                <value code='CP'>Current Price</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "    </loop>\n"
                + "    <loop code='PID'>\n"
                + "        <segment code='PID'>\n"
                + "            <name>Product/Item Description</name>\n"
                + "            <element code='349'>\n"
                + "                <name>Item Description Type</name>\n"
                + "                <value code='F'>Free-form</value>\n"
                + "            </element>\n"
                + "            <element code='352'>\n"
                + "                <name>Description</name>\n"
                + "                <value>MotherBoards</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "    </loop>\n"
                + "    <segment code='CTP'>\n"
                + "        <name>Pricing Information</name>\n"
                + "        <element code=''>\n"
                + "            <name>Price Multiplier Qualifier</name>\n"
                + "            <value code='DIS'>Discount Multiplier</value>\n"
                + "        </element>\n"
                + "        <element code='649'>\n"
                + "            <name>Multiplier</name>\n"
                + "            <value>120</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <loop code='SCH'>\n"
                + "        <segment code='SCH'>\n"
                + "            <name>Line Item Schedule</name>\n"
                + "            <element code='380'>\n"
                + "                <name>Quantity</name>\n"
                + "                <value>10.0</value>\n"
                + "            </element>\n"
                + "            <element code='355'>\n"
                + "                <name>Unit or Basis for Measurement Code</name>\n"
                + "                <value code='TN'>Ton</value>\n"
                + "            </element>\n"
                + "            <element code='374'>\n"
                + "                <name>Date/Time Qualifier</name>\n"
                + "                <value>Delivery Requested</value>\n"
                + "            </element>\n"
                + "            <element code='373'>\n"
                + "                <name>Date</name>\n"
                + "                <value>2013-11-19</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "    </loop>\n"
                + "    <segment code='CTT'>\n"
                + "        <name>Transaction Totals</name>\n"
                + "        <element code='354'>\n"
                + "            <name>Number of Line Items</name>\n"
                + "            <value>1</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='SE'>\n"
                + "        <name>Transaction Set Trailer</name>\n"
                + "        <element code='96'>\n"
                + "            <name>Number of Included Segments</name>\n"
                + "            <value>121</value>\n"
                + "        </element>\n"
                + "        <element code='329'>\n"
                + "            <name>Transaction Set Control Number</name>\n"
                + "            <value>11</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "</transactionSet>";
        SmProperties.folderPath = path;

        String filePath = SmProperties.folderPath + "company-" + tocompanyKey + File.separator + "transaction";
        File folder = new File(filePath);
        if (!folder.exists()) {
            folder.mkdirs();
        }

        String fileLocation = filePath + File.separator + fileName + ".xml";
        writeFile(fileLocation, data);

        SmProperties.folderPath = path;

        String filePath2 = SmProperties.folderPath + "company-" + fromcompanyKey + File.separator + "transaction";
        File folder2 = new File(filePath2);
        if (!folder2.exists()) {
            folder2.mkdirs();
        }

        String fileLocation2 = filePath2 + File.separator + fileName + ".xml";
        writeFile(fileLocation2, data);
    }

    public static void generatePO(String transKey, String path, String fileName, String fromcompanyKey, String tocompanyKey) {
        String data = "<?xml version='1.0' encoding='UTF-8' standalone='no'?>\n"
                + "<transactionSet>\n"
                + "    <segment code='ST'>\n"
                + "        <name>Transaction Set Header</name>\n"
                + "        <element code='143'>\n"
                + "            <name>Transaction Set Identifier Code</name>\n"
                + "            <value>Purchase Order</value>\n"
                + "        </element>\n"
                + "        <element code='329'>\n"
                + "            <name>Transaction Set Control Number</name>\n"
                + "            <value>8</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code=''>\n"
                + "        <name>Beginning Segment for Purchase Order</name>\n"
                + "        <element code='353'>\n"
                + "            <name>Transaction Set Purpose Code</name>\n"
                + "            <value>Original</value>\n"
                + "        </element>\n"
                + "        <element code='92'>\n"
                + "            <name>Purchase Order Type Code</name>\n"
                + "            <value code='NE'> New Order</value>\n"
                + "        </element>\n"
                + "        <element code='324'>\n"
                + "            <name>Purchase Order Number</name>\n"
                + "            <value>8</value>\n"
                + "        </element>\n"
                + "        <element code='373'>\n"
                + "            <name>Date</name>\n"
                + "            <value>2013-11-19</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='CUR'>\n"
                + "        <name>Currency</name>\n"
                + "        <element code='98'>\n"
                + "            <name>Entity Identifier Code</name>\n"
                + "            <value>Buying Party</value>\n"
                + "            <value>US Dollar</value>\n"
                + "        </element>\n"
                + "        <element code='100'>\n"
                + "            <name>Currency Code</name>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='REF'>\n"
                + "        <name>Reference Identification</name>\n"
                + "        <element code='128'>\n"
                + "            <name>Reference Identification Qualifier</name>\n"
                + "            <value>Vendor ID Number</value>\n"
                + "        </element>\n"
                + "        <element code='127'>\n"
                + "            <name>Reference Identification</name>\n"
                + "            <value>980002334</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='PER'>\n"
                + "        <name>Administrative Communications Contact</name>\n"
                + "        <element code='366'>\n"
                + "            <name>Contact Function Code</name>\n"
                + "            <value code='EB'>Entered By</value>\n"
                + "        </element>\n"
                + "        <element code='93'>\n"
                + "            <name>Name</name>\n"
                + "            <value>Manish, Inc</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <loop code='N1'>\n"
                + "        <segment code='N1'>\n"
                + "            <name>Name</name>\n"
                + "            <element code='98'>\n"
                + "                <name>Entity Identifier Code</name>\n"
                + "                <value code='BY'>Buying Party</value>\n"
                + "            </element>\n"
                + "            <element code='93'>\n"
                + "                <name>Name</name>\n"
                + "                <value>Aayush Varma</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N3'>\n"
                + "            <name>Address Information</name>\n"
                + "            <element code='166'>\n"
                + "                <name>Address Information</name>\n"
                + "                <value/>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N4'>\n"
                + "            <name>Geographic Location</name>\n"
                + "            <element code='19'>\n"
                + "                <name>City Name</name>\n"
                + "                <value>Noida</value>\n"
                + "            </element>\n"
                + "            <element code='156'>\n"
                + "                <name>State or Province Code</name>\n"
                + "                <value>null</value>\n"
                + "            </element>\n"
                + "            <element code='116'>\n"
                + "                <name>Postal Code</name>\n"
                + "                <value>1100203</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N1'>\n"
                + "            <name>Name</name>\n"
                + "            <element code='98'>\n"
                + "                <name>Entity Identifier Code</name>\n"
                + "                <value code='VN'>Vendor</value>\n"
                + "            </element>\n"
                + "            <element code='93'>\n"
                + "                <name>Name</name>\n"
                + "                <value>Manish Varma</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N3'>\n"
                + "            <name>Address Information</name>\n"
                + "            <element code='166'>\n"
                + "                <name>Address Information</name>\n"
                + "                <value/>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N4'>\n"
                + "            <name>Geographic Location</name>\n"
                + "            <element code='19'>\n"
                + "                <name>City Name</name>\n"
                + "                <value>Noida</value>\n"
                + "            </element>\n"
                + "            <element code='156'>\n"
                + "                <name>State or Province Code</name>\n"
                + "                <value>null</value>\n"
                + "            </element>\n"
                + "            <element code='116'>\n"
                + "                <name>Postal Code</name>\n"
                + "                <value>110030</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "    </loop>\n"
                + "    <segment code='DTM'>\n"
                + "        <name>Effective Date Time Reference</name>\n"
                + "        <element code='374'>\n"
                + "            <name>Date/Time Qualifier</name>\n"
                + "            <value>Effective Date</value>\n"
                + "        </element>\n"
                + "        <element code='373'>\n"
                + "            <name>Date</name>\n"
                + "            <value>2013-11-19</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='AMT'>\n"
                + "        <name>Monetary Amount</name>\n"
                + "        <element code=''>\n"
                + "            <name>Amount  Qualifier Code</name>\n"
                + "            <value code='TT'>Total Transaction Amount</value>\n"
                + "            <value>1320.0</value>\n"
                + "        </element>\n"
                + "        <element code='782'>\n"
                + "            <name>Monetary Amount</name>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <loop code='PO1'>\n"
                + "        <segment code='PO1'>\n"
                + "            <name>Baseline Item Data</name>\n"
                + "            <element code='350'>\n"
                + "                <name>Assigned Identification</name>\n"
                + "                <value>1</value>\n"
                + "            </element>\n"
                + "            <element code='330'>\n"
                + "                <name>Quantity Ordered</name>\n"
                + "                <value>10.0</value>\n"
                + "            </element>\n"
                + "            <element code='355'>\n"
                + "                <name>Unit or Basis for Measurement Code</name>\n"
                + "                <value>DOZ</value>\n"
                + "            </element>\n"
                + "            <element code='235'>\n"
                + "                <name>Product/Service ID Qualifier</name>\n"
                + "                <value code='MG'>Manufacturer's Part Number</value>\n"
                + "            </element>\n"
                + "            <element code='234'>\n"
                + "                <name>Product/Service ID</name>\n"
                + "                <value>002</value>\n"
                + "            </element>\n"
                + "            <element code='212'>\n"
                + "                <name>Unit Price</name>\n"
                + "                <value>1200.0</value>\n"
                + "            </element>\n"
                + "            <element code='639'>\n"
                + "                <name>Basis of Unit Price Code</name>\n"
                + "                <value code='CP'>Current Price</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "    </loop>\n"
                + "    <loop code='PID'>\n"
                + "        <segment code='PID'>\n"
                + "            <name>Product/Item Description</name>\n"
                + "            <element code='349'>\n"
                + "                <name>Item Description Type</name>\n"
                + "                <value code='F'>Free-form</value>\n"
                + "            </element>\n"
                + "            <element code='352'>\n"
                + "                <name>Description</name>\n"
                + "                <value>MotherBoards</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "    </loop>\n"
                + "    <segment code='CTP'>\n"
                + "        <name>Pricing Information</name>\n"
                + "        <element code=''>\n"
                + "            <name>Price Multiplier Qualifier</name>\n"
                + "            <value code='DIS'>Discount Multiplier</value>\n"
                + "        </element>\n"
                + "        <element code='649'>\n"
                + "            <name>Multiplier</name>\n"
                + "            <value>1</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='CTT'>\n"
                + "        <name>Transaction Totals</name>\n"
                + "        <element code='354'>\n"
                + "            <name>Number of Line Items</name>\n"
                + "            <value>1</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='SE'>\n"
                + "        <name>Transaction Set Trailer</name>\n"
                + "        <element code='96'>\n"
                + "            <name>Number of Included Segments</name>\n"
                + "            <value>121</value>\n"
                + "        </element>\n"
                + "        <element code='329'>\n"
                + "            <name>Transaction Set Control Number</name>\n"
                + "            <value>8</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "</transactionSet>";
        SmProperties.folderPath = path;

        String filePath = SmProperties.folderPath + "company-" + tocompanyKey + File.separator + "transaction";
        File folder = new File(filePath);
        if (!folder.exists()) {
            folder.mkdirs();
        }

        String fileLocation = filePath + File.separator + fileName + ".xml";
        writeFile(fileLocation, data);

        SmProperties.folderPath = path;

        String filePath2 = SmProperties.folderPath + "company-" + fromcompanyKey + File.separator + "transaction";
        File folder2 = new File(filePath2);
        if (!folder2.exists()) {
            folder2.mkdirs();
        }

        String fileLocation2 = filePath2 + File.separator + fileName + ".xml";
        writeFile(fileLocation2, data);
    }

    public static void generateINV(String transKey, String path, String fileName, String fromcompanyKey, String tocompanyKey) {
        String data = "<?xml version='1.0' encoding='UTF-8' standalone='no'?>\n"
                + "<transactionSet>\n"
                + "    <segment code='ST'>\n"
                + "        <name>Transaction Set Header</name>\n"
                + "        <element code='143'>\n"
                + "            <name>Transaction Set Identifier Code</name>\n"
                + "            <value>Invoice</value>\n"
                + "        </element>\n"
                + "        <element code='329'>\n"
                + "            <name>Transaction Set Control Number</name>\n"
                + "            <value>1</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='BIG'>\n"
                + "        <name>Beginning Segment Invoice</name>\n"
                + "        <element code=''>\n"
                + "            <name>Invoice Date</name>\n"
                + "            <value>2015-01-15</value>\n"
                + "        </element>\n"
                + "        <element code='76'>\n"
                + "            <name>Invoice Number</name>\n"
                + "            <value>2015-1</value>\n"
                + "        </element>\n"
                + "        <element code=''>\n"
                + "            <name>P.O Date</name>\n"
                + "            <value>2015-01-15</value>\n"
                + "        </element>\n"
                + "        <element code='324'>\n"
                + "            <name>Purchase Order Number</name>\n"
                + "            <value>232323</value>\n"
                + "        </element>\n"
                + "        <element code='640'>\n"
                + "            <name>Transaction Type Code</name>\n"
                + "            <value code='PR'>Invoice Product</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='CUR'>\n"
                + "        <name>Currency</name>\n"
                + "        <element code='98'>\n"
                + "            <name>Entity Identifier Code</name>\n"
                + "            <value>Buying Party</value>\n"
                + "            <value>US Dollar</value>\n"
                + "        </element>\n"
                + "        <element code='100'>\n"
                + "            <name>Currency Code</name>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='REF'>\n"
                + "        <name>Reference Identification</name>\n"
                + "        <element code='128'>\n"
                + "            <name>Reference Identification Qualifier</name>\n"
                + "            <value>Vendor ID Number</value>\n"
                + "        </element>\n"
                + "        <element code='127'>\n"
                + "            <name>Reference Identification</name>\n"
                + "            <value>123456</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='PER'>\n"
                + "        <name>Administrative Communications Contact</name>\n"
                + "        <element code='366'>\n"
                + "            <name>Contact Function Code</name>\n"
                + "            <value code='EB'>Entered By</value>\n"
                + "        </element>\n"
                + "        <element code='93'>\n"
                + "            <name>Name</name>\n"
                + "            <value>edukrit</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <loop code='N1'>\n"
                + "        <segment code='N1'>\n"
                + "            <name>Name</name>\n"
                + "            <element code='98'>\n"
                + "                <name>Entity Identifier Code</name>\n"
                + "                <value code='BY'>Buying Party</value>\n"
                + "            </element>\n"
                + "            <element code='93'>\n"
                + "                <name>Name</name>\n"
                + "                <value>lok esh</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N3'>\n"
                + "            <name>Address Information</name>\n"
                + "            <element code='166'>\n"
                + "                <name>Address Information</name>\n"
                + "                <value/>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N4'>\n"
                + "            <name>Geographic Location</name>\n"
                + "            <element code='19'>\n"
                + "                <name>City Name</name>\n"
                + "                <value/>\n"
                + "            </element>\n"
                + "            <element code=''>\n"
                + "                <name>State or Province Code</name>\n"
                + "                <value/>\n"
                + "            </element>\n"
                + "            <element code='116'>\n"
                + "                <name>Postal Code</name>\n"
                + "                <value/>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N1'>\n"
                + "            <name>Name</name>\n"
                + "            <element code='98'>\n"
                + "                <name>Entity Identifier Code</name>\n"
                + "                <value code='VN'>Vendor</value>\n"
                + "            </element>\n"
                + "            <element code='93'>\n"
                + "                <name>Name</name>\n"
                + "                <value>eee aaa</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N3'>\n"
                + "            <name>Address Information</name>\n"
                + "            <element code='166'>\n"
                + "                <name>Address Information</name>\n"
                + "                <value>sdfsd</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "        <segment code='N4'>\n"
                + "            <name>Geographic Location</name>\n"
                + "            <element code='19'>\n"
                + "                <name>City Name</name>\n"
                + "                <value>fsdfsdfs</value>\n"
                + "            </element>\n"
                + "            <element code=''>\n"
                + "                <name>State or Province Code</name>\n"
                + "                <value>sdfsdf</value>\n"
                + "            </element>\n"
                + "            <element code='116'>\n"
                + "                <name>Postal Code</name>\n"
                + "                <value>223232</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "    </loop>\n"
                + "    <segment code=''>\n"
                + "        <name>EffectiveDate Time Reference</name>\n"
                + "        <element code='374'>\n"
                + "            <name>Date/Time Qualifier</name>\n"
                + "            <value>Effective Date</value>\n"
                + "            <value>2015-01-15</value>\n"
                + "        </element>\n"
                + "        <element code='373'>\n"
                + "            <name>Date</name>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='AMT'>\n"
                + "        <name>Monetary Amount</name>\n"
                + "        <element code=''>\n"
                + "            <name>Amount  Qualifier Code</name>\n"
                + "            <value code='TT'>Total Transaction Amount</value>\n"
                + "            <value>4978.6</value>\n"
                + "        </element>\n"
                + "        <element code='782'>\n"
                + "            <name>Monetary Amount</name>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='CAD'>\n"
                + "        <name>Carrier Details</name>\n"
                + "        <element code='140'>\n"
                + "            <name>Standard Carrier Alpha Code</name>\n"
                + "            <value>00</value>\n"
                + "        </element>\n"
                + "        <element code='387'>\n"
                + "            <name>Routing</name>\n"
                + "            <value>3434</value>\n"
                + "        </element>\n"
                + "        <element code='128'>\n"
                + "            <name>Reference Identification Qualifier</name>\n"
                + "            <value code='BM'>Bill of Landing Number</value>\n"
                + "        </element>\n"
                + "        <element code=''>\n"
                + "            <name>Reference Identification</name>\n"
                + "            <value code='BM'>34</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <loop code='IT1'>\n"
                + "        <segment code='IT1'>\n"
                + "            <name>Baseline Item Data</name>\n"
                + "            <element code='350'>\n"
                + "                <name>Assigned Identification</name>\n"
                + "                <value>1</value>\n"
                + "            </element>\n"
                + "            <element code='358'>\n"
                + "                <name>Quantity Invoiced</name>\n"
                + "                <value>23.0</value>\n"
                + "            </element>\n"
                + "            <element code='355'>\n"
                + "                <name>Unit or Basis for Measurement Code</name>\n"
                + "                <value code='TN'>BAL</value>\n"
                + "            </element>\n"
                + "            <element code='235'>\n"
                + "                <name>Product/Service ID Qualifier</name>\n"
                + "                <value code='MG'>Manufacturer's Part Number</value>\n"
                + "            </element>\n"
                + "            <element code='234'>\n"
                + "                <name>Product/Service ID</name>\n"
                + "                <value>23</value>\n"
                + "            </element>\n"
                + "            <element code='212'>\n"
                + "                <name>Unit Price</name>\n"
                + "                <value>23.0</value>\n"
                + "            </element>\n"
                + "            <element code='639'>\n"
                + "                <name>Basis of Unit Price Code</name>\n"
                + "                <value code='CP'>Current Price</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "    </loop>\n"
                + "    <loop code='PID'>\n"
                + "        <segment code='PID'>\n"
                + "            <name>Product/Item Description</name>\n"
                + "            <element code='349'>\n"
                + "                <name>Item Description Type</name>\n"
                + "                <value code='F'>Free-form</value>\n"
                + "            </element>\n"
                + "            <element code='352'>\n"
                + "                <name>Description</name>\n"
                + "                <value>23</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "    </loop>\n"
                + "    <loop code='IT1'>\n"
                + "        <segment code='IT1'>\n"
                + "            <name>Baseline Item Data</name>\n"
                + "            <element code='350'>\n"
                + "                <name>Assigned Identification</name>\n"
                + "                <value>1</value>\n"
                + "            </element>\n"
                + "            <element code='358'>\n"
                + "                <name>Quantity Invoiced</name>\n"
                + "                <value>34.0</value>\n"
                + "            </element>\n"
                + "            <element code='355'>\n"
                + "                <name>Unit or Basis for Measurement Code</name>\n"
                + "                <value code='TN'>CMS</value>\n"
                + "            </element>\n"
                + "            <element code='235'>\n"
                + "                <name>Product/Service ID Qualifier</name>\n"
                + "                <value code='MG'>Manufacturer's Part Number</value>\n"
                + "            </element>\n"
                + "            <element code='234'>\n"
                + "                <name>Product/Service ID</name>\n"
                + "                <value>34</value>\n"
                + "            </element>\n"
                + "            <element code='212'>\n"
                + "                <name>Unit Price</name>\n"
                + "                <value>34.0</value>\n"
                + "            </element>\n"
                + "            <element code='639'>\n"
                + "                <name>Basis of Unit Price Code</name>\n"
                + "                <value code='CP'>Current Price</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "    </loop>\n"
                + "    <loop code='PID'>\n"
                + "        <segment code='PID'>\n"
                + "            <name>Product/Item Description</name>\n"
                + "            <element code='349'>\n"
                + "                <name>Item Description Type</name>\n"
                + "                <value code='F'>Free-form</value>\n"
                + "            </element>\n"
                + "            <element code='352'>\n"
                + "                <name>Description</name>\n"
                + "                <value>34</value>\n"
                + "            </element>\n"
                + "        </segment>\n"
                + "    </loop>\n"
                + "    <segment code='CTP'>\n"
                + "        <name>Pricing Information</name>\n"
                + "        <element code=''>\n"
                + "            <name>Price Multiplier Qualifier</name>\n"
                + "            <value code='DIS'>Discount Multiplier</value>\n"
                + "        </element>\n"
                + "        <element code='649'>\n"
                + "            <name>Multiplier</name>\n"
                + "            <value>2</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='CTT'>\n"
                + "        <name>Transaction Totals</name>\n"
                + "        <element code='354'>\n"
                + "            <name>Number of Line Items</name>\n"
                + "            <value>2</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "    <segment code='SE'>\n"
                + "        <name>Transaction Set Trailer</name>\n"
                + "        <element code='96'>\n"
                + "            <name>Number of Included Segments</name>\n"
                + "            <value>151</value>\n"
                + "        </element>\n"
                + "        <element code='329'>\n"
                + "            <name>Transaction Set Control Number</name>\n"
                + "            <value>1</value>\n"
                + "        </element>\n"
                + "    </segment>\n"
                + "</transactionSet>";
        SmProperties.folderPath = path;

        String filePath = SmProperties.folderPath + "company-" + tocompanyKey + File.separator + "transaction";
        File folder = new File(filePath);
        if (!folder.exists()) {
            folder.mkdirs();
        }

        String fileLocation = filePath + File.separator + fileName + ".xml";
        writeFile(fileLocation, data);

        SmProperties.folderPath = path;

        String filePath2 = SmProperties.folderPath + "company-" + fromcompanyKey + File.separator + "transaction";
        File folder2 = new File(filePath2);
        if (!folder2.exists()) {
            folder2.mkdirs();
        }

        String fileLocation2 = filePath2 + File.separator + fileName + ".xml";
        writeFile(fileLocation2, data);
    }

    public static void writeFile(String file, String data) {
        try {
            FileWriter fileWriter = null;
            PrintWriter printWriter = null;
            fileWriter = new FileWriter(file);
            printWriter = new PrintWriter(fileWriter);
            printWriter.println(data);

            printWriter.close();
        } catch (Exception ex) {
            ErrorMaster.insert("Exception at writeFile in GenerateEDI : " + ex.getMessage());
        }
    }

    public static String generateEDI(String path, String companyKey) {
        String downloadFileName = "EDI_" + System.currentTimeMillis() + ".zip";
        String ozf = path + File.separator + downloadFileName;
        String sf = path;
        Zipper appZip = new Zipper(ozf, sf);
        appZip.generateFileList();
        appZip.zipIt();
        return downloadFileName;
    }

}
