/**
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Copyright (c) 2006-2013 Tekton Technologies (P) Ltd. All Rights Reserved.
 * This product and related documentation is protected by copyright and
 * distributed under licenses restricting its use, copying, distribution and
 * decompilation. No part of this product or related documentation may be
 * reproduced in any form by any means without prior written authorization of
 * Tekton Technologies (P) Ltd. and its licensors, if any.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */

package db.trans;

import java.sql.Date;
import java.sql.Timestamp;
import utils.ErrorMaster;

/**
 * File:  PORecord.java 
 *
 * Created on Jul 4, 2013 2:23:20 PM
 */

public class PORecord
{
	// This is the transaction id
	public long     transId_;

	// This is the unique id of this PO
	public long     poId_;
	
	// This is the unique id of this PO which is automatically generated by code
	public String   poNum_;

	// This is the companyRegnKey who sent the PO request
	public String   from_;

	// This is the companyRegnKey who receive the PO request
	public String   to_;

	// This is the userProfileKey who sent the PO request
	public String   userFrom_;

	// This is the userProfileKey who receive the PO request
	public String  	userTo_;

	// Current status of the PO request
	public String	status_;

	/*
	 * This is the current action of the transaction.It should be Accept or
	 * Reject or Inquire
	 */
	public String 	action_;

	/*
	 * This flag is set to true if PO send to outside supplier who is not
	 * registered with SupplyMedium. Flag set to false PO send to registered
	 * supplier
	 */
	public int      isOutsideSupplier_;

	/* Email id for outside supplier */
	public String   outsideSupplierEmail_;
        
        public String            outsideSuppliercountry;
        
        public String            outsideSupplierstate;
        
        public String            outsideSuppliercity;
        
        public String            outsideSupplieraddress;
        
        public String            outsideSupplierzipcode;

	// This string indicate the recurring type
	public String   recurring_;

	// PO Date
	public Date     poDate_;
	
	// Total amount of the PO with out tax amount
	public double 	totalListPrice_;  
	
	// Percentage of tax for PO
	public double 	taxPercentage_;
	
	// Total amount of the PO with tax amount
	public double 	totalPrice_;
	
	// This is the PO form added in SM date
	public Timestamp	createdTimestamp_;
	
	 // It is indicate that Invoice create or not for this PO. If this value 1
    // Invoice created otherwise not at all
    public int isInvoiceCreated_;
    
    private static ErrorMaster errorMaster_ = null;



	/*
	 * Method : PORecord -- constructor
	 * 
	 * Input  : None
	 * 
	 * Return : None
	 * 
	 * Purpose:
	 */
	
	public PORecord( )
	{
		if( errorMaster_ == null ) errorMaster_ = new ErrorMaster( );
	}
	
	/*
	 * Method : show( ) 
	 * 
	 * Input : None 
	 * 
	 * Return : None
	 * 
	 * Purpose: It is used to print the all class variable values in console
	 */

	public void show( )
	{
		errorMaster_.insert( "transId_				= " + transId_ );
		errorMaster_.insert( "poId_					= " + poId_ );
		errorMaster_.insert( "poNum_                 = " + poNum_);
		
		errorMaster_.insert( "from					= " + from_.toString( ) );
		errorMaster_.insert( "to						= " + to_.toString( ) );
		
		errorMaster_.insert( "userFrom				= " + userFrom_.toString( ) );
		errorMaster_.insert( "userTo					= " + userTo_.toString( ) );
		
		errorMaster_.insert( "status_				= " + status_ );
		
		errorMaster_.insert( "isOutsideSupplier_		= " + isOutsideSupplier_ );
		errorMaster_.insert( "outsideSupplierEmail_	= " + outsideSupplierEmail_ );
		
		errorMaster_.insert( "recurring_				= " + recurring_ );
		errorMaster_.insert( "poDate_				= " + poDate_ );
		errorMaster_.insert( "createdTimestamp_		= " + createdTimestamp_ );
		
		errorMaster_.insert( "totalListPrice_		= " + totalListPrice_ );
		errorMaster_.insert( "taxPercentage_			= " + taxPercentage_ );
		errorMaster_.insert( "totalPrice_			= " + totalPrice_ );
		
		errorMaster_.insert( "isInvoiceCreated_		= " + isInvoiceCreated_ );
		
	}
	
	
	/*
	 * Method : clear( ) 
	 * 
	 * Input : None 
	 * 
	 * Return : None
	 * 
	 * Purpose: To reset the class variables.
	 */
	
	public void clear( )
	{
		transId_ 				= -1;
		poId_	 				= -1;
		poNum_					= null;
		
		from_ 					= null;
		to_ 					= null;
		
		userFrom_ 				= null;
		userTo_					= null;
		
		status_ 				= null;
		
		isOutsideSupplier_ 		= -1;
		outsideSupplierEmail_ 	= null;
                outsideSuppliercountry 	= null;
                outsideSupplierstate 	= null;
                outsideSuppliercity 	= null;
                outsideSupplieraddress 	= null;
                outsideSupplierzipcode 	= null;
		
		recurring_ 				= null;
		poDate_ 				= null;
		createdTimestamp_ 		= null;
		
		totalListPrice_ 		= 0.0f;
		taxPercentage_ 			= 0.0f;
		totalPrice_ 			= 0.0f;
		
		isInvoiceCreated_ = 0;
	}
}
